# Generated by Django 6.0.2 on 2026-02-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
